name: Build and Deploy iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.22.1 --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"

      - name: Run Flutter Doctor
        run: flutter doctor

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create export options plist
        run: |
          cat <<EOF > exportOptions.plist
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>$APP_STORE_CONNECT_TEAM_ID</string>
            <key>uploadBitcode</key>
            <true/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>automatic</string>
          </dict>
          </plist>
          EOF

      - name: Archive and Export IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $PWD/build/Runner.xcarchive

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Runner.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $PWD/build/Runner.ipa

      - name: Upload to App Store Connect
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
        run: |
          xcrun altool --upload-app \
                       --type ios \
                       --file $PWD/build/Runner.ipa/Runner.ipa \
                       --apiKey $APP_STORE_CONNECT_API_KEY \
                       --apiIssuer $APP_STORE_CONNECT_API_ISSUER_ID
